# Generated by Django 4.2.2 on 2023-06-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ApiApp",
            "0003_rename_івано_франківська_ukrainealarmsstatus_cherkasy_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UkraineRegions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("Region", models.CharField(max_length=30)),
                ("Region_en", models.CharField(max_length=30)),
                ("Alarm", models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name="UkraineAlarmsStatus",
        ),
    ]
