# Generated by Django 4.2 on 2023-06-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiApp", "0004_ukraineregions_delete_ukrainealarmsstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ukraineregions",
            name="datetime",
            field=models.CharField(max_length=50),
        ),
    ]
